const questions=[
 {icon:'🔐',mission:'Mission 1 · Password Power-Up',question:'Which password has the strongest shield?',answers:['football10','Blue!Rocket7Cloud','Joshua2016'],correct:1,tip:'Long, surprising passwords with mixed characters are harder to guess.'},
 {icon:'🕵️',mission:'Mission 2 · Scam Scanner',question:'A pop-up says “You won! Click NOW and enter your address.” What should you do?',answers:['Click quickly','Share it with friends','Close it and tell a trusted adult'],correct:2,tip:'Pause before you click. If something feels strange, ask a trusted adult.'},
 {icon:'👣',mission:'Mission 3 · Footprint Quest',question:'Which post leaves the best digital footprint?',answers:['A kind comment on a class project','A photo showing your home address','An angry message about a friend'],correct:0,tip:'Every post leaves a trail. Be kind, protect private information, and think first.'}
];
const params=new URLSearchParams(location.search);const mode=params.get('mode')||'setup';
let state={screen:'intro',q:0,answered:false,choice:null,score:0,started:false,startAt:0,muted:false};let audienceWindow=null,audio=null,timerId=null;
const channel='BroadcastChannel'in window?new BroadcastChannel('heritage-arcade'):null;
function send(){localStorage.setItem('heritageArcadeState',JSON.stringify({...state,t:Date.now()}));channel?.postMessage(state)}
function receive(s){if(mode!=='setup'&&s){state={...state,...s};render()}}
channel&&(channel.onmessage=e=>receive(e.data));addEventListener('storage',e=>{if(e.key==='heritageArcadeState')receive(JSON.parse(e.newValue||'{}'))});
function logo(){return '<img class="logo" src="heritage-logo.png" alt="Heritage Academy">'}
function progress(){return `<div class="progress">${questions.map((_,i)=>`<span class="dot ${i<state.q||(state.screen==='celebrate')?'done':''}"></span>`).join('')}</div>`}
function shell(content){return `<div class="shell"><header class="topbar"><div class="brand">${logo()}<span class="brandtext">DIGITAL LITERACY ARCADE</span></div><span class="pill">${state.screen==='intro'?'READY PLAYER ONE':state.screen==='celebrate'?'QUEST COMPLETE':`LEVEL ${state.q+1} / 3`}</span></header><section class="stage">${content}</section>${progress()}</div>`}
function intro(){return shell(`<div class="card"><div class="eyebrow">Heritage Academy presents</div><h1 class="title">Digital<br>Defenders</h1><p class="subtitle">Three arcade missions. One important power: making smart, safe and kind choices online.</p><div class="stars">★ ★ ★</div><p class="tip">Player: press SPACE to begin</p></div>`)}
function game(){const q=questions[state.q];return shell(`<div class="card"><div class="mission-icon">${q.icon}</div><div class="eyebrow">${q.mission}</div><h1 class="subtitle" style="font-weight:900">${q.question}</h1><div class="answers">${q.answers.map((a,i)=>`<button class="answer ${state.answered?(i===q.correct?'correct':i===state.choice?'wrong':''):''}" data-choice="${i}" ${state.answered?'disabled':''}><span class="key">${i+1}</span>${a}</button>`).join('')}</div>${state.answered?`<div class="feedback">${state.choice===q.correct?'POWER-UP EARNED! ⚡':'GOOD TRY — SHIELD UPDATED! 🛡️'}</div><div class="tip">${q.tip}</div><div class="tip">Press SPACE for the next mission</div>`:''}</div>`)}
function celebrate(){return shell(`<div class="card"><div class="confetti"></div><div style="position:relative"><div class="badge">🛡️</div><div class="eyebrow" style="margin-top:20px">Achievement unlocked</div><h1 class="title">Digital<br>Defender!</h1><p class="subtitle">At Heritage Academy, we learn to stay safe, think before we click, and leave a positive digital footprint.</p><div class="stars">${'★ '.repeat(Math.max(1,state.score))}</div><p class="tip">Smart • Safe • Kind • Ready</p></div></div>`)}
function audience(){document.getElementById('app').innerHTML=state.screen==='intro'?intro():state.screen==='question'?game():celebrate();document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(+b.dataset.choice))}
function notes(){if(state.screen==='intro')return '<h2>Welcome (30 sec)</h2><p>“Who is ready to become a Digital Defender?” Ask everyone to call out the three powers: <b>smart, safe, kind</b>.</p>';if(state.screen==='celebrate')return '<h2>Celebrate (45 sec)</h2><p>Lead a cheer: “Think first! Stay safe! Be kind!” Explain that these are skills students build in Digital Literacy at Heritage Academy.</p>';const q=questions[state.q];return `<h2>${q.mission}</h2><p>Read the question aloud. Let the room discuss, then invite the player to press 1, 2 or 3.</p><p><b>Reveal:</b> ${q.tip}</p>`}
function presenter(){const elapsed=state.started?Math.floor((Date.now()-state.startAt)/1000):0,remaining=Math.max(0,300-elapsed);document.getElementById('app').innerHTML=`<div class="presenter"><section class="panel"><div class="topbar">${logo()}<div><div class="timer">${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}</div><div class="small">5-minute guide</div></div></div><div class="preview"><div><div class="mission-icon">${state.screen==='intro'?'🎮':state.screen==='celebrate'?'🏆':questions[state.q].icon}</div><h1>${state.screen==='intro'?'Opening screen':state.screen==='celebrate'?'Celebration screen':questions[state.q].mission}</h1><p class="status">Audience display ${audienceWindow&&!audienceWindow.closed?'connected':'opens in a separate window'}</p></div></div><div class="control-grid" style="margin-top:18px"><button class="action" id="open">Open audience display</button><button class="action secondary" id="full">Fullscreen audience</button><button class="action" id="next">${state.screen==='intro'?'Start game':state.answered?'Next':'Reveal / advance'}</button><button class="action secondary" id="mute">${state.muted?'Sound off':'Sound on'}</button><button class="action secondary" id="reset">Reset game</button><button class="action secondary" id="celebrate">Jump to celebration</button></div><p class="small">Keyboard: 1–3 answer · Space advances · M mutes · R resets</p></section><aside class="panel notes">${notes()}<hr style="border-color:#ffffff22"><h2>Score</h2><p class="stars">${'★ '.repeat(state.score)}${'☆ '.repeat(3-state.score)}</p><p>Classmates can call out their ideas; the player makes the final selection.</p></aside></div>`;bindPresenter();if(!timerId)timerId=setInterval(()=>{if(mode==='presenter')presenter()},1000)}
function setup(){document.getElementById('app').innerHTML=shell(`<div class="card setup"><div class="eyebrow">Two-screen setup</div><h1 class="subtitle" style="font-weight:900">Ready the Digital Arcade</h1><ol><li>Connect the second monitor and choose <b>Extend</b> display.</li><li>Click below to open the presenter controls.</li><li>In the controls, open the audience display and drag it to monitor 2.</li><li>Make the audience window full screen and turn on the speaker.</li></ol><button class="action" id="launch">Launch presenter controls</button><p class="small">Everything runs offline. Chrome or Edge recommended.</p></div>`);document.getElementById('launch').onclick=()=>location.href='?mode=presenter'}
function bindPresenter(){document.getElementById('open').onclick=()=>{audienceWindow=open('?mode=audience','heritageAudience','popup,width=1280,height=720');setTimeout(send,400)};document.getElementById('full').onclick=()=>{if(!audienceWindow||audienceWindow.closed)audienceWindow=open('?mode=audience','heritageAudience');audienceWindow?.focus();try{audienceWindow?.document.documentElement.requestFullscreen()}catch{}};document.getElementById('next').onclick=advance;document.getElementById('mute').onclick=toggleMute;document.getElementById('reset').onclick=reset;document.getElementById('celebrate').onclick=()=>{state.screen='celebrate';send();sound('win');render()}}
function choose(i){if(state.screen!=='question'||state.answered)return;state.choice=i;state.answered=true;if(i===questions[state.q].correct)state.score++;sound(i===questions[state.q].correct?'correct':'wrong');send();render()}
function advance(){if(state.screen==='intro'){state.screen='question';state.started=true;state.startAt=Date.now();startMusic()}else if(state.screen==='question'&&!state.answered){return}else if(state.screen==='question'&&state.q<2){state.q++;state.answered=false;state.choice=null;sound('next')}else{state.screen='celebrate';sound('win')}send();render()}
function reset(){state={screen:'intro',q:0,answered:false,choice:null,score:0,started:false,startAt:0,muted:state.muted};send();render()}
function ctx(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();return audio}
function beep(freq,dur,type='square',vol=.045,delay=0){if(state.muted)return;const c=ctx(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+delay+dur);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+dur)}
function sound(type){if(type==='correct'){beep(523,.12);beep(659,.12,'square',.045,.12);beep(784,.22,'square',.05,.24)}else if(type==='wrong'){beep(220,.18,'sawtooth');beep(165,.28,'sawtooth',.04,.16)}else if(type==='win'){[523,659,784,1047].forEach((f,i)=>beep(f,.3,'square',.05,i*.16))}else beep(440,.12)}
function startMusic(){if(state.muted||window.musicLoop)return;let n=0;const playNote=()=>{if(!state.muted&&state.screen!=='celebrate'){const seq=[262,330,392,330,294,370,440,370];beep(seq[n++%seq.length],.16,'triangle',.018)}};playNote();window.musicLoop=setInterval(playNote,260)}
function toggleMute(){state.muted=!state.muted;if(!state.muted){sound('next');startMusic()}send();render()}
function render(){mode==='audience'?audience():mode==='presenter'?presenter():setup()}
addEventListener('pointerdown',()=>{if(mode==='presenter')startMusic()},{once:true});
addEventListener('keydown',e=>{if(mode==='setup')return;if(mode==='presenter')startMusic();if(['1','2','3'].includes(e.key))choose(+e.key-1);if(e.code==='Space'){e.preventDefault();advance()}if(e.key.toLowerCase()==='m')toggleMute();if(e.key.toLowerCase()==='r')reset()});
if(mode==='audience'){const saved=localStorage.getItem('heritageArcadeState');if(saved)receive(JSON.parse(saved))}render();
